controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    robot1_iiwa_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    robot2_iiwa_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot1_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    robot2_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    robot1_impedance_controller:
      type: impedance_controller/ImpedanceController
    
    robot2_impedance_controller:
     type: impedance_controller/ImpedanceController

    ets_state_broadcaster:
      type: external_torque_sensor_broadcaster/ExternalTorqueSensorBroadcaster

robot1_iiwa_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - robot1_joint_a1
      - robot1_joint_a2
      - robot1_joint_a3
      - robot1_joint_a4
      - robot1_joint_a5
      - robot1_joint_a6
      - robot1_joint_a7

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

robot2_iiwa_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - robot2_joint_a1
      - robot2_joint_a2
      - robot2_joint_a3
      - robot2_joint_a4
      - robot2_joint_a5
      - robot2_joint_a6
      - robot2_joint_a7

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

robot1_velocity_controller:
  ros__parameters:
    joints:
      - robot1_joint_a1
      - robot1_joint_a2
      - robot1_joint_a3
      - robot1_joint_a4
      - robot1_joint_a5
      - robot1_joint_a6
      - robot1_joint_a7

robot2_velocity_controller:
  ros__parameters:
    joints:
      - robot2_joint_a1
      - robot2_joint_a2
      - robot2_joint_a3
      - robot2_joint_a4
      - robot2_joint_a5
      - robot2_joint_a6
      - robot2_joint_a7

robot1_impedance_controller:
  ros__parameters:
    joints:
      - robot1_joint_a1
      - robot1_joint_a2
      - robot1_joint_a3
      - robot1_joint_a4
      - robot1_joint_a5
      - robot1_joint_a6
      - robot1_joint_a7
    stiffness: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
    damping: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]


robot2_impedance_controller:
  ros__parameters:
    joints:
      - robot2_joint_a1
      - robot2_joint_a2
      - robot2_joint_a3
      - robot2_joint_a4
      - robot2_joint_a5
      - robot2_joint_a6
      - robot2_joint_a7

ets_state_broadcaster:
  ros__parameters:
    sensor_name: external_torque_sensor
