# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  robot2_joint_a1: 0.0
  robot2_joint_a2: 0.0
  robot2_joint_a3: 0.0
  robot2_joint_a4: 0.0
  robot2_joint_a5: 0.0
  robot2_joint_a6: 0.0
  robot2_joint_a7: 0.0