# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - robot1_controller
    - robot2_controller

  robot1_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot1_joint_a1
      - robot1_joint_a2
      - robot1_joint_a3
      - robot1_joint_a4
      - robot1_joint_a5
      - robot1_joint_a6
      - robot1_joint_a7
  robot2_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot2_joint_a1
      - robot2_joint_a2
      - robot2_joint_a3
      - robot2_joint_a4
      - robot2_joint_a5
      - robot2_joint_a6
      - robot2_joint_a7