/**:
  ros__parameters:
    moveit_controller_manager:
        moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - robot1_iiwa_arm_controller
        - robot2_iiwa_arm_controller

      robot1_iiwa_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - robot1_joint_a1
          - robot1_joint_a2
          - robot1_joint_a3
          - robot1_joint_a4
          - robot1_joint_a5
          - robot1_joint_a6
          - robot1_joint_a7

      robot2_iiwa_arm_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        default: true
        joints:
          - robot2_joint_a1
          - robot2_joint_a2
          - robot2_joint_a3
          - robot2_joint_a4
          - robot2_joint_a5
          - robot2_joint_a6
          - robot2_joint_a7
